from enum import unique
from sqlalchemy import Column, Integer,String ,Boolean , TIME ,Date,BigInteger,ForeignKey, ARRAY
from sqlalchemy.sql.expression import text
from sqlalchemy.sql.sqltypes import TIMESTAMP
from dbconnect.db import Base
from sqlalchemy.orm import relationship
    
class user(Base):
    __tablename__="user_data"
    
    id=Column(Integer,primary_key=True,nullable=False)
    name=Column(String,nullable=False)
    gender=Column(String,nullable=False)
    dob=Column(Date,nullable=False)
    mobile=Column(BigInteger,nullable=False)
    email=Column(String,nullable=False,unique=True)
    username=Column(String,nullable=False , unique=True)
    password=Column(String,nullable=False)
    role=Column(Integer,nullable=False )
    district=Column(String,nullable=False)
    time=Column(TIMESTAMP,nullable=False,server_default=text('now()'))
        
    
class schoolProfile(Base):
    __tablename__ = "SchoolProfile"
    
    owner = relationship("user")
    
    id=Column(Integer,primary_key=True,nullable=False)
    user_id=Column(Integer,ForeignKey("user_data.id",ondelete="CASCADE"), nullable=False)
    username = Column(String,nullable=True , unique=True)
    name=Column(String,nullable=True)
    post=Column(String,nullable=True)
    district=Column(String,nullable=True)
    state=Column(String,nullable=True)
    ctv=Column(String,nullable=True)
    pincode=Column(BigInteger,nullable=True)
    url=Column(String,nullable=True)
    mail=Column(String,nullable=True)
    mobile=Column(BigInteger,nullable=True)
    type=Column(String,nullable=True)
    needs=Column(String,nullable=True)
    academic=Column(String,nullable=True)
    establish=Column(String,nullable=True)
    level=Column(ARRAY(String),nullable=True)
    medium=Column(ARRAY(String),nullable=True)
    affiliation=Column(String,nullable=True)
    t_staff=Column(Integer,nullable=True)
    gender=Column(String,nullable=True)
    girl=Column(Integer,nullable=True)
    boys=Column(Integer,nullable=True)
    total=Column(Integer,nullable=True)
    n_staff=Column(Integer,nullable=True)
    correspondent_name=Column(String,nullable=True)
    correspondent_mobile=Column(BigInteger,nullable=True)
    correspondent_mail=Column(String,nullable=True)
    principal_name=Column(String,nullable=True)
    principal_mail=Column(String,nullable=True)
    principal_office_mobile=Column(BigInteger,nullable=True)
    principal_mobile=Column(BigInteger,nullable=True)
    recognized=Column(String,nullable=True)
    board_name=Column(String,nullable=True)
    affiliate_number=Column(String,nullable=True)
    affiliate_year=Column(Integer,nullable=True)
    affiliate_type=Column(String,nullable=True)
    affiliate_state=Column(String,nullable=True)
    christian=Column(Integer,nullable=True)
    hindu=Column(Integer,nullable=True)
    islam=Column(Integer,nullable=True)
    others=Column(Integer,nullable=True)
    nonBeliver=Column(Integer,nullable=True)
    fire=Column(String,nullable=True)
    sanitation=Column(String,nullable=True)
    building=Column(String,nullable=True)
    minority=Column(String,nullable=True)
    own=Column(String,nullable=True)
    trust_name=Column(String,nullable=True)
    trust_register=Column(String,nullable=True)
    register_act=Column(String,nullable=True)
    register_year=Column(Integer,nullable=True)
    register_no=Column(String,nullable=True)
    register_validity=Column(Integer,nullable=True)
    president_name=Column(String,nullable=True)
    president_designation=Column(String,nullable=True)
    president_address=Column(String,nullable=True)
    president_number=Column(BigInteger,nullable=True)
    president_email=Column(String,nullable=True)
    gover_trust=Column(String,nullable=True)
    gover_member=Column(Integer,nullable=True)
    gover_tenure=Column(Integer,nullable=True)
    educative=Column(String,nullable=True)
    educative_member=Column(Integer,nullable=True)
    educative_tenure=Column(Integer,nullable=True)
    pta=Column(String,nullable=True)
    pta_member=Column(Integer,nullable=True)
    pta_tenure=Column(Integer,nullable=True)
    student_council=Column(String,nullable=True)
    student_member=Column(Integer,nullable=True)
    student_tenure=Column(Integer,nullable=True)
    general_complaint=Column(String,nullable=True)
    school_commit=Column(String,nullable=True)
    constitution_commit=Column(String,nullable=True)
    constitution_member=Column(Integer,nullable=True)
    constitution_tenure=Column(Integer,nullable=True)
    school_building=Column(String,nullable=True)
    schoolArea=Column(String,nullable=True)
    schoolBuilt=Column(String,nullable=True)
    groundArea=Column(String,nullable=True)
    noBuilding=Column(Integer,nullable=True)
    provision=Column(Integer,nullable=True)
    noStaircase=Column(Integer,nullable=True)
    lift=Column(Integer,nullable=True)
    classRoom=Column(Integer,nullable=True)
    staffRoom=Column(Integer,nullable=True)
    physicalLab=Column(Integer,nullable=True)
    chemistryLab=Column(Integer,nullable=True)
    biologylab=Column(Integer,nullable=True)
    mathsLab=Column(Integer,nullable=True)
    science=Column(Integer,nullable=True)
    library=Column(Integer,nullable=True)
    auditorium=Column(Integer,nullable=True)
    counselor=Column(Integer,nullable=True)
    parlor=Column(Integer,nullable=True)
    prayer=Column(Integer,nullable=True)
    sick=Column(Integer,nullable=True)
    canteen=Column(Integer,nullable=True)
    security=Column(Integer,nullable=True)
    otherRoom=Column(Integer,nullable=True)
    staffToilets=Column(Integer,nullable=True)
    studToilet=Column(Integer,nullable=True)
    teacher=Column(String,nullable=True)
    boundry=Column(String,nullable=True)
    boundry_wall=Column(String,nullable=True)
    cctv=Column(String,nullable=True)
    dataSave=Column(String,nullable=True)
    camera=Column(Integer,nullable=True)
    maleGuard=Column(String,nullable=True)
    noMaleGuard=Column(Integer,nullable=True)
    femaleGuard=Column(String,nullable=True)
    noFemaleGuard=Column(Integer,nullable=True)
    drinkWater=Column(String,nullable=True)
    drainage=Column(String,nullable=True)
    midday=Column(String,nullable=True)
    nobus=Column(Integer,nullable=True)
    gps=Column(Integer,nullable=True)
    noladyAttend=Column(Integer,nullable=True)
    firstAid=Column(Integer,nullable=True)
    noDrinkWater=Column(Integer,nullable=True)
    BusContract=Column(Integer,nullable=True)
    buspass=Column(String,nullable=True)
    freeTransport=Column(String,nullable=True)
    library_open=Column(TIME,nullable=True)
    library_close=Column(TIME,nullable=True)
    noBook=Column(Integer,nullable=True)
    magazine=Column(Integer,nullable=True)
    noNews=Column(Integer,nullable=True)
    noEbook=Column(Integer,nullable=True)
    primaryLibrary=Column(String,nullable=True)
    remedial=Column(String,nullable=True)
    tv=Column(Boolean,nullable=True)
    digitalboard=Column(Boolean,nullable=True)
    computer=Column(Boolean,nullable=True)
    projector=Column(Boolean,nullable=True)
    tape = Column(Boolean,nullable=True)
    ppm = Column(Integer,nullable=True)
    ppf = Column(Integer,nullable=True)
    tpm = Column(Integer,nullable=True)
    tpf = Column(Integer,nullable=True)
    pvm = Column(Integer,nullable=True)
    pvf = Column(Integer,nullable=True)
    tvm = Column(Integer,nullable=True)
    tvf = Column(Integer,nullable=True)
    ppgtm = Column(Integer,nullable=True)
    ppgtf = Column(Integer,nullable=True)
    tpgtm = Column(Integer,nullable=True)
    tpgtf = Column(Integer,nullable=True)
    ptgtm = Column(Integer,nullable=True)
    ptgtf = Column(Integer,nullable=True)
    ttgtm = Column(Integer,nullable=True)
    ttgtf = Column(Integer,nullable=True)
    pprtm = Column(Integer,nullable=True)
    pprtf = Column(Integer,nullable=True)
    tprtm = Column(Integer,nullable=True)
    tprtf = Column(Integer,nullable=True)
    pnttm = Column(Integer,nullable=True)
    pnttf = Column(Integer,nullable=True)
    tnttm = Column(Integer,nullable=True)
    tnttf = Column(Integer,nullable=True)
    putm = Column(Integer,nullable=True)
    putf = Column(Integer,nullable=True)
    tutm = Column(Integer,nullable=True)
    tutf = Column(Integer,nullable=True)
    plm = Column(Integer,nullable=True)
    plf = Column(Integer,nullable=True)
    tlm = Column(Integer,nullable=True)
    tlf = Column(Integer,nullable=True)
    pmtm = Column(Integer,nullable=True)
    pmtf = Column(Integer,nullable=True)
    tmtm = Column(Integer,nullable=True)
    tmtf = Column(Integer,nullable=True)
    pctm = Column(Integer,nullable=True)
    pctf = Column(Integer,nullable=True)
    tctm = Column(Integer,nullable=True)
    tctf = Column(Integer,nullable=True)
    pcltm = Column(Integer,nullable=True)
    pcltf = Column(Integer,nullable=True)
    tcltm = Column(Integer,nullable=True)
    tcltf = Column(Integer,nullable=True)
    pfmm = Column(Integer,nullable=True)
    pfmf = Column(Integer,nullable=True)
    tfmm = Column(Integer,nullable=True)
    tfmf = Column(Integer,nullable=True)
    pnm = Column(Integer,nullable=True)
    pnf = Column(Integer,nullable=True)
    tnm = Column(Integer,nullable=True)
    tnf = Column(Integer,nullable=True)
    pptm = Column(Integer,nullable=True)
    pptf = Column(Integer,nullable=True)
    tptm = Column(Integer,nullable=True)
    tptf = Column(Integer,nullable=True)
    pom = Column(Integer,nullable=True)
    tom = Column(Integer,nullable=True)
    ptom = Column(Integer,nullable=True)
    poa = Column(Integer,nullable=True)
    toa = Column(Integer,nullable=True)
    ptoa = Column(Integer,nullable=True)
    pc = Column(Integer,nullable=True)
    tc = Column(Integer,nullable=True)
    ptc = Column(Integer,nullable=True)
    pla = Column(Integer,nullable=True)
    tla = Column(Integer,nullable=True)
    ptla = Column(Integer,nullable=True)
    pa = Column(Integer,nullable=True)
    ta = Column(Integer,nullable=True)
    ptac = Column(Integer,nullable=True)
    ppc = Column(Integer,nullable=True)
    tpc = Column(Integer,nullable=True)
    ptpc = Column(Integer,nullable=True)
    po = Column(Integer,nullable=True)
    to = Column(Integer,nullable=True)
    pto = Column(Integer,nullable=True)
    no_of_act=Column(Integer,nullable=True)
    no_of_group=Column(Integer,nullable=True)
    no_of_service=Column(Integer,nullable=True)
    school_sports=Column(Integer,nullable=True)
    zonal_sports=Column(Integer,nullable=True)
    district_sports=Column(Integer,nullable=True)
    state_sports=Column(Integer,nullable=True)
    national_sports=Column(Integer,nullable=True)
    international_sports=Column(Integer,nullable=True)
    school_compet=Column(Integer,nullable=True)
    zonal_compet=Column(Integer,nullable=True)
    district_compet=Column(Integer,nullable=True)
    state_compet=Column(Integer,nullable=True)
    national_compet=Column(Integer,nullable=True)
    international_compet=Column(Integer,nullable=True)
    school_program=Column(Integer,nullable=True)
    zonal_program=Column(Integer,nullable=True)
    district_program=Column(Integer,nullable=True)
    state_program=Column(Integer,nullable=True)
    national_program=Column(Integer,nullable=True)
    international_program=Column(Integer,nullable=True)
    school_history=Column(String , nullable=True)
    school_plan=Column(String,nullable=True)
    academic_begin_month=Column(String,nullable=True)
    academic_end_month=Column(String,nullable=True)
    no_of_work_2021=Column(Integer,nullable=True)
    no_of_work_2020=Column(Integer,nullable=True)
    no_of_work_2019=Column(Integer,nullable=True)
    no_of_hour_2021=Column(Integer,nullable=True)
    no_of_hour_2020=Column(Integer,nullable=True)
    no_of_hour_2019=Column(Integer,nullable=True)
    no_of_totalhour_2021=Column(Integer,nullable=True)
    no_of_totalhour_2020=Column(Integer,nullable=True)
    no_of_totalhour_2019=Column(Integer,nullable=True)
    no_of_dayStaff_2021=Column(Integer,nullable=True)
    no_of_dayStaff_2020=Column(Integer,nullable=True)
    no_of_dayStaff_2019=Column(Integer,nullable=True)
    no_of_holiday_2021=Column(Integer,nullable=True)
    no_of_holiday_2020=Column(Integer,nullable=True)
    no_of_holiday_2019=Column(Integer,nullable=True)
    no_of_subject=Column(Integer,nullable=True)
    no_of_moral=Column(Integer,nullable=True)
    teach_time=Column(Integer,nullable=True)
    no_of_activity=Column(Integer,nullable=True)
    from_summer_time=Column(TIME,nullable=True)
    to_summer_time=Column(TIME,nullable=True)
    from_winter_time=Column(TIME,nullable=True)
    to_winter_time=Column(TIME,nullable=True)
    school_shift=Column(String,nullable=True)
    scholarship=Column(ARRAY(String), nullable=True)
    shift=Column(ARRAY(String),nullable=True)
    schoolClass=Column(ARRAY(String),nullable=True)