from sqlalchemy import Column, Integer,String ,Boolean , TIME ,Date,BigInteger,ForeignKey, ARRAY
from sqlalchemy.sql.expression import text
from sqlalchemy.sql.sqltypes import TIMESTAMP
from Model.userModel.user import Base,User

from sqlalchemy.orm import relationship
    
class SchoolProfile(Base):
    __tablename__ = "SchoolProfile"
    owner = relationship('User')
    
    id=Column(Integer,primary_key=True,nullable=False)
    user_id=Column(Integer,ForeignKey("user_data.id",ondelete="CASCADE"), nullable=False)
    username = Column(String,nullable=True , unique=True)
    permanentPrincipalMale = Column(Integer,nullable=True)
    permanentPrincipalFemale = Column(Integer,nullable=True)
    temporaryPrincipalMale = Column(Integer,nullable=True)
    temporaryPrincipalFemale = Column(Integer,nullable=True)
    permanentVicePrincipalMale = Column(Integer,nullable=True)
    permanentVicePrincipalFemale = Column(Integer,nullable=True)
    temporaryVicePrincipalMale = Column(Integer,nullable=True)
    temporaryVicePrincipalFemale = Column(Integer,nullable=True)
    permanentPGTMale = Column(Integer,nullable=True)
    permanentPGTFemale = Column(Integer,nullable=True)
    temporaryPGTMale = Column(Integer,nullable=True)
    temporaryPGTFemale = Column(Integer,nullable=True)
    permanentTGTMale = Column(Integer,nullable=True)
    permanentTGTFemale = Column(Integer,nullable=True)
    temporaryTGTMale = Column(Integer,nullable=True)
    temporaryTGTFemale = Column(Integer,nullable=True)
    permanentPRTMale = Column(Integer,nullable=True)
    permanentPRTFemale = Column(Integer,nullable=True)
    temporaryPRTMale = Column(Integer,nullable=True)
    temporaryPRTFemale = Column(Integer,nullable=True)
    permanentNTTMale = Column(Integer,nullable=True)
    permanentNTTFemale = Column(Integer,nullable=True)
    temporaryNTTMale = Column(Integer,nullable=True)
    temporaryNTTFemale = Column(Integer,nullable=True)
    permanentUntrainedTeacherMale = Column(Integer,nullable=True)
    permanentUntrainedTeacherFemale = Column(Integer,nullable=True)
    temporaryUntrainedTeacherMale = Column(Integer,nullable=True)
    temporaryUntrainedTeacherFemale = Column(Integer,nullable=True)
    permanentLibrarianMale = Column(Integer,nullable=True)
    permanentLibrarianFemale = Column(Integer,nullable=True)
    temporaryLibrarianMale = Column(Integer,nullable=True)
    temporaryLibrarianFemale = Column(Integer,nullable=True)
    permanentMusicTeacherMale = Column(Integer,nullable=True)
    permanentMusicTeacherFemale = Column(Integer,nullable=True)
    temporaryMusicTeacherMale = Column(Integer,nullable=True)
    temporaryMusicTeacherFemale = Column(Integer,nullable=True)
    permanentCounsellorMale = Column(Integer,nullable=True)
    permanentCounsellorFemale = Column(Integer,nullable=True)
    temporaryCounsellorMale = Column(Integer,nullable=True)
    temporaryCounsellorFemale = Column(Integer,nullable=True)
    permanentComputerLiteracyMale = Column(Integer,nullable=True)
    permanentComputerLiteracyFemale = Column(Integer,nullable=True)
    temporaryComputerLiteracyMale = Column(Integer,nullable=True)
    temporaryComputerLiteracyFemale = Column(Integer,nullable=True)
    permanentFaithMinisterMale = Column(Integer,nullable=True)
    permanentFaithMinisterFemale = Column(Integer,nullable=True)
    temporaryFaithMinisterMale = Column(Integer,nullable=True)
    temporaryFaithMinisterFemale = Column(Integer,nullable=True)
    permanentNurseMale = Column(Integer,nullable=True)
    permanentNurseFemale = Column(Integer,nullable=True)
    temporaryNurseMale = Column(Integer,nullable=True)
    temporaryNurseFemale = Column(Integer,nullable=True)
    permanentPTTeacherMale = Column(Integer,nullable=True)
    permanentPTTeacherFemale = Column(Integer,nullable=True)
    temporaryPTTeacherMale = Column(Integer,nullable=True)
    temporaryPTTeacherFemale = Column(Integer,nullable=True)
    