from sqlalchemy import Column, Integer,String ,Boolean , TIME ,Date,BigInteger,ForeignKey, ARRAY
from sqlalchemy.sql.expression import text
from sqlalchemy.sql.sqltypes import TIMESTAMP
from Model.userModel.user import Base,User

from sqlalchemy.orm import relationship
    
class SchoolProfile(Base):
    __tablename__ = "SchoolProfile"
    owner = relationship('User')
    
    id=Column(Integer,primary_key=True,nullable=False)
    user_id=Column(Integer,ForeignKey("user_data.id",ondelete="CASCADE"), nullable=False)
    username = Column(String,nullable=True , unique=True)
    institutionName=Column(String,nullable=True)
    postalAddress=Column(String,nullable=True)
    district=Column(String,nullable=True)
    state=Column(String,nullable=True)
    cityVillageTown=Column(String,nullable=True)
    pincode=Column(BigInteger,nullable=True)
    url=Column(String,nullable=True)
    officeMail=Column(String,nullable=True)
    officeMobile=Column(BigInteger,nullable=True)
    schoolLocation=Column(String,nullable=True)
    childNeeds=Column(String,nullable=True)
    academicYear=Column(String,nullable=True)    
    establishYear=Column(String,nullable=True)
    schoolLevel=Column(ARRAY(String),nullable=True)
    medium=Column(ARRAY(String),nullable=True)
    affiliationNature=Column(String,nullable=True)
    teachingStaff=Column(Integer,nullable=True)
    gender=Column(String,nullable=True)
    noGirls=Column(Integer,nullable=True)
    noBoys=Column(Integer,nullable=True)
    totalStudent=Column(Integer,nullable=True)
    nonTeachingStaff=Column(Integer,nullable=True)
    correspondentName=Column(String,nullable=True)
    correspondentMobileNo=Column(BigInteger,nullable=True)
    correspondentMailId=Column(String,nullable=True)
    principalName=Column(String,nullable=True)
    principalMailId=Column(String,nullable=True)
    principalOfficeMobileNo=Column(BigInteger,nullable=True)
    principalMobileNo=Column(BigInteger,nullable=True)
    recognizedByGovern=Column(String,nullable=True)
    boardName=Column(String,nullable=True)
    affiliationNumber=Column(String,nullable=True)
    affiliationYear=Column(Integer,nullable=True)
    affiliationType=Column(String,nullable=True)
    affiliationStatement=Column(String,nullable=True)
    christian=Column(Integer,nullable=True)
    hindu=Column(Integer,nullable=True)
    islam=Column(Integer,nullable=True)
    others=Column(Integer,nullable=True)
    nonBeliver=Column(Integer,nullable=True)
    fire=Column(String,nullable=True)
    sanitation=Column(String,nullable=True)
    building=Column(String,nullable=True)
    minority=Column(String,nullable=True)
    schoolOwned=Column(String,nullable=True)
    trustName=Column(String,nullable=True)
    trustRegistered=Column(String,nullable=True)
    registeredAct=Column(String,nullable=True)
    registerYear=Column(Integer,nullable=True)
    registerNo=Column(String,nullable=True)
    registrationValidity=Column(Integer,nullable=True)
    presidentName=Column(String,nullable=True)
    presidentDesignation=Column(String,nullable=True)
    presidentAddress=Column(String,nullable=True)
    presidentNumber=Column(BigInteger,nullable=True)
    presidentEmail=Column(String,nullable=True)
    governingTrust=Column(String,nullable=True)
    governingMember=Column(Integer,nullable=True)
    governingTenure=Column(Integer,nullable=True)
    educativeCommunity=Column(String,nullable=True)
    educativeCommunityMember=Column(Integer,nullable=True)
    educativeCommunityTenure=Column(Integer,nullable=True)
    pta=Column(String,nullable=True)
    ptaMember=Column(Integer,nullable=True)
    ptaTenure=Column(Integer,nullable=True)
    studentCouncil=Column(String,nullable=True)
    studentMember=Column(Integer,nullable=True)
    studentTenure=Column(Integer,nullable=True)
    generalComplaint=Column(String,nullable=True)
    schoolCommit=Column(String,nullable=True)
    constitutionCommit=Column(String,nullable=True)
    constitutionMember=Column(Integer,nullable=True)
    constitutionTenure=Column(Integer,nullable=True)
    schoolBuilding=Column(String,nullable=True)
    schoolArea=Column(String,nullable=True)
    schoolBuilt=Column(String,nullable=True)
    groundArea=Column(String,nullable=True)
    noBuilding=Column(Integer,nullable=True)
    provision=Column(Integer,nullable=True)
    noStaircase=Column(Integer,nullable=True)
    noLift=Column(Integer,nullable=True)
    schoolHistory=Column(String , nullable=True)
    schoolPlan=Column(String,nullable=True)
    classRoom=Column(Integer,nullable=True)
    staffRoom=Column(Integer,nullable=True)
    physicalLab=Column(Integer,nullable=True)
    chemistryLab=Column(Integer,nullable=True)
    biologylab=Column(Integer,nullable=True)
    mathsLab=Column(Integer,nullable=True)
    scienceLab=Column(Integer,nullable=True)
    library=Column(Integer,nullable=True)
    auditorium=Column(Integer,nullable=True)
    counselor=Column(Integer,nullable=True)
    parlor=Column(Integer,nullable=True)
    prayer=Column(Integer,nullable=True)
    sick=Column(Integer,nullable=True)
    canteen=Column(Integer,nullable=True)
    security=Column(Integer,nullable=True)
    otherRoom=Column(Integer,nullable=True)
    staffToilets=Column(Integer,nullable=True)
    studToilet=Column(Integer,nullable=True)
    teacher=Column(String,nullable=True)
    boundryWall=Column(String,nullable=True)
    boundryWallStatus=Column(String,nullable=True)
    cctv=Column(String,nullable=True)
    dataSave=Column(String,nullable=True)
    noCamera=Column(Integer,nullable=True)
    maleGuard=Column(String,nullable=True)
    noMaleGuard=Column(Integer,nullable=True)
    femaleGuard=Column(String,nullable=True)
    noFemaleGuard=Column(Integer,nullable=True)
    drinkWater=Column(String,nullable=True)
    drainage=Column(String,nullable=True)
    middayScheme=Column(String,nullable=True)
    noOwnBus=Column(Integer,nullable=True)
    gpsCamera=Column(Integer,nullable=True)
    noladyAttend=Column(Integer,nullable=True)
    firstAid=Column(Integer,nullable=True)
    noDrinkWater=Column(Integer,nullable=True)
    BusContract=Column(Integer,nullable=True)
    buspass=Column(String,nullable=True)
    freeTransport=Column(String,nullable=True)
    libraryOpenTime=Column(TIME,nullable=True)
    libraryCloseTime=Column(TIME,nullable=True)
    noBook=Column(Integer,nullable=True)
    noMagazine=Column(Integer,nullable=True)
    noNews=Column(Integer,nullable=True)
    noEbook=Column(Integer,nullable=True)
    primaryLibrary=Column(String,nullable=True)
    remedial=Column(String,nullable=True)
    tv=Column(Boolean,nullable=True)
    digitalboard=Column(Boolean,nullable=True)
    computer=Column(Boolean,nullable=True)
    projector=Column(Boolean,nullable=True)
    tape = Column(Boolean,nullable=True)
    permanentPrincipalMale = Column(Integer,nullable=True)
    permanentPrincipalFemale = Column(Integer,nullable=True)
    temporaryPrincipalMale = Column(Integer,nullable=True)
    temporaryPrincipalFemale = Column(Integer,nullable=True)
    permanentVicePrincipalMale = Column(Integer,nullable=True)
    permanentVicePrincipalFemale = Column(Integer,nullable=True)
    temporaryVicePrincipalMale = Column(Integer,nullable=True)
    temporaryVicePrincipalFemale = Column(Integer,nullable=True)
    permanentPGTMale = Column(Integer,nullable=True)
    permanentPGTFemale = Column(Integer,nullable=True)
    temporaryPGTMale = Column(Integer,nullable=True)
    temporaryPGTFemale = Column(Integer,nullable=True)
    permanentTGTMale = Column(Integer,nullable=True)
    permanentTGTFemale = Column(Integer,nullable=True)
    temporaryTGTMale = Column(Integer,nullable=True)
    temporaryTGTFemale = Column(Integer,nullable=True)
    permanentPRTMale = Column(Integer,nullable=True)
    permanentPRTFemale = Column(Integer,nullable=True)
    temporaryPRTMale = Column(Integer,nullable=True)
    temporaryPRTFemale = Column(Integer,nullable=True)
    permanentNTTMale = Column(Integer,nullable=True)
    permanentNTTFemale = Column(Integer,nullable=True)
    temporaryNTTMale = Column(Integer,nullable=True)
    temporaryNTTFemale = Column(Integer,nullable=True)
    permanentUntrainedTeacherMale = Column(Integer,nullable=True)
    permanentUntrainedTeacherFemale = Column(Integer,nullable=True)
    temporaryUntrainedTeacherMale = Column(Integer,nullable=True)
    temporaryUntrainedTeacherFemale = Column(Integer,nullable=True)
    permanentLibrarianMale = Column(Integer,nullable=True)
    permanentLibrarianFemale = Column(Integer,nullable=True)
    temporaryLibrarianMale = Column(Integer,nullable=True)
    temporaryLibrarianFemale = Column(Integer,nullable=True)
    permanentMusicTeacherMale = Column(Integer,nullable=True)
    permanentMusicTeacherFemale = Column(Integer,nullable=True)
    temporaryMusicTeacherMale = Column(Integer,nullable=True)
    temporaryMusicTeacherFemale = Column(Integer,nullable=True)
    permanentCounsellorMale = Column(Integer,nullable=True)
    permanentCounsellorFemale = Column(Integer,nullable=True)
    temporaryCounsellorMale = Column(Integer,nullable=True)
    temporaryCounsellorFemale = Column(Integer,nullable=True)
    permanentComputerLiteracyMale = Column(Integer,nullable=True)
    permanentComputerLiteracyFemale = Column(Integer,nullable=True)
    temporaryComputerLiteracyMale = Column(Integer,nullable=True)
    temporaryComputerLiteracyFemale = Column(Integer,nullable=True)
    permanentFaithMinisterMale = Column(Integer,nullable=True)
    permanentFaithMinisterFemale = Column(Integer,nullable=True)
    temporaryFaithMinisterMale = Column(Integer,nullable=True)
    temporaryFaithMinisterFemale = Column(Integer,nullable=True)
    permanentNurseMale = Column(Integer,nullable=True)
    permanentNurseFemale = Column(Integer,nullable=True)
    temporaryNurseMale = Column(Integer,nullable=True)
    temporaryNurseFemale = Column(Integer,nullable=True)
    permanentPTTeacherMale = Column(Integer,nullable=True)
    permanentPTTeacherFemale = Column(Integer,nullable=True)
    temporaryPTTeacherMale = Column(Integer,nullable=True)
    temporaryPTTeacherFemale = Column(Integer,nullable=True)
    permanentOfficeManager = Column(Integer,nullable=True)
    temporaryOfficeManager = Column(Integer,nullable=True)
    partTimeOfficeManager = Column(Integer,nullable=True)
    permanentOfficeAssistant = Column(Integer,nullable=True)
    temporaryOfficeAssistant = Column(Integer,nullable=True)
    partTimeOfficeAssistant = Column(Integer,nullable=True)
    permanentClerk = Column(Integer,nullable=True)
    temporaryClerk = Column(Integer,nullable=True)
    partTimeClerk = Column(Integer,nullable=True)
    permanentLabAttendants = Column(Integer,nullable=True)
    temporaryLabAttendants = Column(Integer,nullable=True)
    partTimeLabAttendants = Column(Integer,nullable=True)
    permanentAccountant = Column(Integer,nullable=True)
    temporaryAccountant = Column(Integer,nullable=True)
    partTimeAccountant = Column(Integer,nullable=True)
    permanentPeonesClerk = Column(Integer,nullable=True)
    temporaryPeonesClerk = Column(Integer,nullable=True)
    partTimePeonesClerk = Column(Integer,nullable=True)
    permanentOthers = Column(Integer,nullable=True)
    temporaryOthers = Column(Integer,nullable=True)
    partTimeOthers = Column(Integer,nullable=True)
    noCurricularActivities=Column(Integer,nullable=True)
    noGroupsPresent=Column(Integer,nullable=True)
    noCommunityService=Column(Integer,nullable=True)
    schoolSports=Column(Integer,nullable=True)
    zonalSports=Column(Integer,nullable=True)
    districtSports=Column(Integer,nullable=True)
    stateSports=Column(Integer,nullable=True)
    nationalSports=Column(Integer,nullable=True)
    internationalSports=Column(Integer,nullable=True)
    schoolCompetition=Column(Integer,nullable=True)
    zonalCompetition=Column(Integer,nullable=True)
    districtCompetition=Column(Integer,nullable=True)
    stateCompetition=Column(Integer,nullable=True)
    nationalCompetition=Column(Integer,nullable=True)
    internationalCompetition=Column(Integer,nullable=True)
    schoolProgram=Column(Integer,nullable=True)
    zonalProgram=Column(Integer,nullable=True)
    districtProgram=Column(Integer,nullable=True)
    stateProgram=Column(Integer,nullable=True)
    nationalProgram=Column(Integer,nullable=True)
    internationalProgram=Column(Integer,nullable=True)
    academicYearStart=Column(String,nullable=True)
    academicYearEnd=Column(String,nullable=True)
    noWorkingDays1=Column(Integer,nullable=True)
    noWorkingDays2=Column(Integer,nullable=True)
    noWorkingDays3=Column(Integer,nullable=True)
    noWorkingHours1=Column(Integer,nullable=True)
    noWorkingHours2=Column(Integer,nullable=True)
    noWorkingHours3=Column(Integer,nullable=True)
    totalHours1=Column(Integer,nullable=True)
    totalHours2=Column(Integer,nullable=True)
    totalHours3=Column(Integer,nullable=True)
    noWorkingDaysForStaff1=Column(Integer,nullable=True)
    noWorkingDaysForStaff2=Column(Integer,nullable=True)
    noWorkingDaysForStaff3=Column(Integer,nullable=True)
    noHolidays1=Column(Integer,nullable=True)
    noHolidays2=Column(Integer,nullable=True)
    noHolidays3=Column(Integer,nullable=True)
    noSubjectPerWeek=Column(Integer,nullable=True)
    noMoralTeachPerWeek=Column(Integer,nullable=True)
    teachingDuration=Column(Integer,nullable=True)
    noHoursForActivity=Column(Integer,nullable=True)
    fromTimeInSummer=Column(TIME,nullable=True)
    toTimeInSummer=Column(TIME,nullable=True)
    fromTimeInWinter=Column(TIME,nullable=True)
    toTimeInWinter=Column(TIME,nullable=True)
    schoolWorkWithShift=Column(String,nullable=True)
    scholarship=Column(ARRAY(String), nullable=True)
    shift=Column(ARRAY(String),nullable=True)
    schoolClass=Column(ARRAY(String),nullable=True)