"""add_info5

Revision ID: 0c278d56219d
Revises: a00695d74b47
Create Date: 2022-09-23 12:28:40.623355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c278d56219d'
down_revision = 'a00695d74b47'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SchoolProfile', sa.Column('governingTrust', sa.String(), nullable=True))
    op.add_column('SchoolProfile', sa.Column('governingMember', sa.Integer(), nullable=True))
    op.add_column('SchoolProfile', sa.Column('governingTenure', sa.Integer(), nullable=True))
    op.add_column('SchoolProfile', sa.Column('educativeCommunity', sa.String(), nullable=True))
    op.add_column('SchoolProfile', sa.Column('educativeCommunityMember', sa.Integer(), nullable=True))
    op.add_column('SchoolProfile', sa.Column('educativeCommunityTenure', sa.Integer(), nullable=True))
    op.add_column('SchoolProfile', sa.Column('pta', sa.String(), nullable=True))
    op.add_column('SchoolProfile', sa.Column('ptaMember', sa.Integer(), nullable=True))
    op.add_column('SchoolProfile', sa.Column('ptaTenure', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('SchoolProfile', 'ptaTenure')
    op.drop_column('SchoolProfile', 'ptaMember')
    op.drop_column('SchoolProfile', 'pta')
    op.drop_column('SchoolProfile', 'educativeCommunityTenure')
    op.drop_column('SchoolProfile', 'educativeCommunityMember')
    op.drop_column('SchoolProfile', 'educativeCommunity')
    op.drop_column('SchoolProfile', 'governingTenure')
    op.drop_column('SchoolProfile', 'governingMember')
    op.drop_column('SchoolProfile', 'governingTrust')
    # ### end Alembic commands ###
