"""add_gengeral3

Revision ID: 6afd93722e39
Revises: be49d53d5450
Create Date: 2022-09-22 20:12:05.783289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6afd93722e39'
down_revision = 'be49d53d5450'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SchoolProfile', sa.Column('recognizedByGovern', sa.String(), nullable=True))
    op.add_column('SchoolProfile', sa.Column('boardName', sa.String(), nullable=True))
    op.add_column('SchoolProfile', sa.Column('affiliationNumber', sa.String(), nullable=True))
    op.add_column('SchoolProfile', sa.Column('affiliationYear', sa.Integer(), nullable=True))
    op.add_column('SchoolProfile', sa.Column('affiliationType', sa.String(), nullable=True))
    op.add_column('SchoolProfile', sa.Column('affiliationStatement', sa.String(), nullable=True))
    op.add_column('SchoolProfile', sa.Column('christian', sa.Integer(), nullable=True))
    op.add_column('SchoolProfile', sa.Column('hindu', sa.Integer(), nullable=True))
    op.add_column('SchoolProfile', sa.Column('islam', sa.Integer(), nullable=True))
    op.add_column('SchoolProfile', sa.Column('others', sa.Integer(), nullable=True))
    op.add_column('SchoolProfile', sa.Column('nonBeliver', sa.Integer(), nullable=True))
    op.add_column('SchoolProfile', sa.Column('fire', sa.String(), nullable=True))
    op.add_column('SchoolProfile', sa.Column('sanitation', sa.String(), nullable=True))
    op.add_column('SchoolProfile', sa.Column('building', sa.String(), nullable=True))
    op.add_column('SchoolProfile', sa.Column('minority', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('SchoolProfile', 'minority')
    op.drop_column('SchoolProfile', 'building')
    op.drop_column('SchoolProfile', 'sanitation')
    op.drop_column('SchoolProfile', 'fire')
    op.drop_column('SchoolProfile', 'nonBeliver')
    op.drop_column('SchoolProfile', 'others')
    op.drop_column('SchoolProfile', 'islam')
    op.drop_column('SchoolProfile', 'hindu')
    op.drop_column('SchoolProfile', 'christian')
    op.drop_column('SchoolProfile', 'affiliationStatement')
    op.drop_column('SchoolProfile', 'affiliationType')
    op.drop_column('SchoolProfile', 'affiliationYear')
    op.drop_column('SchoolProfile', 'affiliationNumber')
    op.drop_column('SchoolProfile', 'boardName')
    op.drop_column('SchoolProfile', 'recognizedByGovern')
    # ### end Alembic commands ###
