"""add_info4

Revision ID: a00695d74b47
Revises: 6afd93722e39
Create Date: 2022-09-23 11:17:38.921222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a00695d74b47'
down_revision = '6afd93722e39'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SchoolProfile', sa.Column('schoolOwned', sa.String(), nullable=True))
    op.add_column('SchoolProfile', sa.Column('trustName', sa.String(), nullable=True))
    op.add_column('SchoolProfile', sa.Column('trustRegistered', sa.String(), nullable=True))
    op.add_column('SchoolProfile', sa.Column('registeredAct', sa.String(), nullable=True))
    op.add_column('SchoolProfile', sa.Column('registerYear', sa.Integer(), nullable=True))
    op.add_column('SchoolProfile', sa.Column('registerNo', sa.String(), nullable=True))
    op.add_column('SchoolProfile', sa.Column('registrationValidity', sa.Integer(), nullable=True))
    op.add_column('SchoolProfile', sa.Column('presidentName', sa.String(), nullable=True))
    op.add_column('SchoolProfile', sa.Column('presidentDesignation', sa.String(), nullable=True))
    op.add_column('SchoolProfile', sa.Column('presidentAddress', sa.String(), nullable=True))
    op.add_column('SchoolProfile', sa.Column('presidentNumber', sa.BigInteger(), nullable=True))
    op.add_column('SchoolProfile', sa.Column('presidentEmail', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('SchoolProfile', 'presidentEmail')
    op.drop_column('SchoolProfile', 'presidentNumber')
    op.drop_column('SchoolProfile', 'presidentAddress')
    op.drop_column('SchoolProfile', 'presidentDesignation')
    op.drop_column('SchoolProfile', 'presidentName')
    op.drop_column('SchoolProfile', 'registrationValidity')
    op.drop_column('SchoolProfile', 'registerNo')
    op.drop_column('SchoolProfile', 'registerYear')
    op.drop_column('SchoolProfile', 'registeredAct')
    op.drop_column('SchoolProfile', 'trustRegistered')
    op.drop_column('SchoolProfile', 'trustName')
    op.drop_column('SchoolProfile', 'schoolOwned')
    # ### end Alembic commands ###
