"""add_others

Revision ID: a296b2273fea
Revises: b8b6066ccf69
Create Date: 2022-09-09 18:57:45.922793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a296b2273fea'
down_revision = 'b8b6066ccf69'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("SchoolProfile",sa.Column("level",sa.ARRAY(sa.String),nullable=True))
    op.add_column("SchoolProfile",sa.Column("medium",sa.ARRAY(sa.String),nullable=True))
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("SchoolProfile","level")
    op.drop_column("SchoolProfile","medium")
    pass
    # ### end Alembic commands ###
