"""add_schoolProfile

Revision ID: be49d53d5450
Revises: 392b2f489a13
Create Date: 2022-09-22 11:35:14.995684

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'be49d53d5450'
down_revision = '392b2f489a13'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SchoolProfile1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('institutionName', sa.String(), nullable=True),
    sa.Column('postalAddress', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('cityVillageTown', sa.String(), nullable=True),
    sa.Column('pincode', sa.BigInteger(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('officeMail', sa.String(), nullable=True),
    sa.Column('officeMobile', sa.BigInteger(), nullable=True),
    sa.Column('schoolLocation', sa.String(), nullable=True),
    sa.Column('childNeeds', sa.String(), nullable=True),
    sa.Column('academicYear', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_data.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('SchoolProfile2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('establishYear', sa.String(), nullable=True),
    sa.Column('schoolLevel', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('medium', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('affiliationNature', sa.String(), nullable=True),
    sa.Column('teachingStaff', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('noGirls', sa.Integer(), nullable=True),
    sa.Column('noBoys', sa.Integer(), nullable=True),
    sa.Column('totalStudent', sa.Integer(), nullable=True),
    sa.Column('nonTeachingStaff', sa.Integer(), nullable=True),
    sa.Column('correspondentName', sa.String(), nullable=True),
    sa.Column('correspondentMobileNo', sa.BigInteger(), nullable=True),
    sa.Column('correspondentMailId', sa.String(), nullable=True),
    sa.Column('principalName', sa.String(), nullable=True),
    sa.Column('principalMailId', sa.String(), nullable=True),
    sa.Column('principalOfficeMobileNo', sa.BigInteger(), nullable=True),
    sa.Column('principalMobileNo', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_data.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SchoolProfile2')
    op.drop_table('SchoolProfile1')
    # ### end Alembic commands ###
